### ISSUE TITLE
MEMORY_ONLY persistence corrupts uasts

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/engine#185]
How to reproduce this on science-3:

```
docker run -it --rm -v /data:/data -v /data/home/vadim/spark:/hashes -e PYSPARK_PYTHON=/usr/bin/python3 --link bblfshd srcd/apollo bags -r /data/siva/test -o /hashes/test#append_smth_here# -f id -l Java -s 'local[20]' --min-docfreq 5 --bblfsh bblfshd
```

works.

```
docker run -it --rm -v /data:/data -v /data/home/vadim/spark:/hashes -e PYSPARK_PYTHON=/usr/bin/python3 --link bblfshd srcd/apollo bags -r /data/siva/test -o /hashes/testt#append_smth_here# -f id -l Java -s 'local[20]' --min-docfreq 5 --bblfsh bblfshd --persist MEMORY_ONLY
```

fails with

```
[Stage 1:>                                                       (0 + 20) / 200]17/11/14 09:49:42 ERROR Executor: Exception in task 15.0 in stage 1.0 (TID 16)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/spark/python/pyspark/rdd.py", line 830, in func
    initial = next(iterator)
  File "/spark/python/pyspark/rdd.py", line 1239, in countPartition
    for obj in iterator:
  File "/packages/ast2vec/ast2vec/repo2/wmhash.py", line 105, in process_row
    for k in extractor.inspect(row.uast):
  File "/packages/ast2vec/ast2vec/repo2/wmhash.py", line 134, in inspect
    bag = self.id2bag.uast_to_bag(uast)
  File "/packages/ast2vec/ast2vec/uast_ids_to_bag.py", line 38, in uast_to_bag
    nodes = bblfsh.filter(uast, roles_filter)
RuntimeError

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/11/14 09:49:42 WARN TaskSetManager: Lost task 15.0 in stage 1.0 (TID 16, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/spark/python/pyspark/rdd.py", line 830, in func
    initial = next(iterator)
  File "/spark/python/pyspark/rdd.py", line 1239, in countPartition
    for obj in iterator:
  File "/packages/ast2vec/ast2vec/repo2/wmhash.py", line 105, in process_row
    for k in extractor.inspect(row.uast):
  File "/packages/ast2vec/ast2vec/repo2/wmhash.py", line 134, in inspect
    bag = self.id2bag.uast_to_bag(uast)
  File "/packages/ast2vec/ast2vec/uast_ids_to_bag.py", line 38, in uast_to_bag
    nodes = bblfsh.filter(uast, roles_filter)
RuntimeError

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

17/11/14 09:49:42 ERROR TaskSetManager: Task 15 in stage 1.0 failed 1 times; aborting job
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_20 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_20 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN TaskSetManager: Lost task 20.0 in stage 1.0 (TID 21, localhost, executor driver): TaskKilled (stage cancelled)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/packages/gemini/__main__.py", line 89, in <module>
    sys.exit(main())
  File "/packages/gemini/__main__.py", line 86, in main
    return handler(args)
  File "/packages/gemini/bags.py", line 38, in source2bags
    pipeline.execute()
  File "/packages/ast2vec/ast2vec/repo2/base.py", line 76, in execute
    return super().execute(files)
  File "/packages/ast2vec/ast2vec/repo2/base.py", line 30, in execute
    results.append(child.execute(new_head))
  File "/packages/ast2vec/ast2vec/repo2/base.py", line 30, in execute
    results.append(child.execute(new_head))
  File "/packages/ast2vec/ast2vec/repo2/base.py", line 27, in execute
    new_head = self(head)
  File "/packages/ast2vec/ast2vec/repo2/wmhash.py", line 91, in __call__
    reduced = processed.countByKey()
  File "/spark/python/pyspark/rdd.py", line 1644, in countByKey
    return self.map(lambda x: x[0]).countByValue()
  File "/spark/python/pyspark/rdd.py", line 1247, in countByValue
    return self.mapPartitions(countPartition).reduce(mergeMaps)
  File "/spark/python/pyspark/rdd.py", line 835, in reduce
    vals = self.mapPartitions(func).collect()
  File "/spark/python/pyspark/rdd.py", line 809, in collect
    port = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/usr/local/lib/python3.5/dist-packages/py4j/java_gateway.py", line 1160, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/py4j/protocol.py", line 320, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 15 in stage 1.0 failed 1 times, most recent failure: Lost task 15.0 in stage 1.0 (TID 16, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/spark/python/pyspark/rdd.py", line 830, in func
    initial = next(iterator)
  File "/spark/python/pyspark/rdd.py", line 1239, in countPartition
    for obj in iterator:
  File "/packages/ast2vec/ast2vec/repo2/wmhash.py", line 105, in process_row
    for k in extractor.inspect(row.uast):
  File "/packages/ast2vec/ast2vec/repo2/wmhash.py", line 134, in inspect
    bag = self.id2bag.uast_to_bag(uast)
  File "/packages/ast2vec/ast2vec/uast_ids_to_bag.py", line 38, in uast_to_bag
    nodes = bblfsh.filter(uast, roles_filter)
RuntimeError

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2087)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:458)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/spark/python/pyspark/rdd.py", line 830, in func
    initial = next(iterator)
  File "/spark/python/pyspark/rdd.py", line 1239, in countPartition
    for obj in iterator:
  File "/packages/ast2vec/ast2vec/repo2/wmhash.py", line 105, in process_row
    for k in extractor.inspect(row.uast):
  File "/packages/ast2vec/ast2vec/repo2/wmhash.py", line 134, in inspect
    bag = self.id2bag.uast_to_bag(uast)
  File "/packages/ast2vec/ast2vec/uast_ids_to_bag.py", line 38, in uast_to_bag
    nodes = bblfsh.filter(uast, roles_filter)
RuntimeError

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_8 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_8 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN TaskSetManager: Lost task 8.0 in stage 1.0 (TID 9, localhost, executor driver): TaskKilled (stage cancelled)
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_6 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_6 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN TaskSetManager: Lost task 6.0 in stage 1.0 (TID 7, localhost, executor driver): TaskKilled (stage cancelled)
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_19 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_19 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN TaskSetManager: Lost task 19.0 in stage 1.0 (TID 20, localhost, executor driver): TaskKilled (stage cancelled)
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_14 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_14 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_4 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_4 could not be removed as it was not found on disk or in memory
Traceback (most recent call last):
  File "/spark/python/lib/pyspark.zip/pyspark/daemon.py", line 157, in manager
  File "/spark/python/lib/pyspark.zip/pyspark/daemon.py", line 61, in worker
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 202, in main
    if read_int(infile) == SpecialLengths.END_OF_STREAM:
  File "/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 577, in read_int
    raise EOFError
EOFError
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_2 failed due to an exception
17/11/14 09:49:42 WARN TaskSetManager: Lost task 14.0 in stage 1.0 (TID 15, localhost, executor driver): TaskKilled (stage cancelled)
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_2 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN TaskSetManager: Lost task 4.0 in stage 1.0 (TID 5, localhost, executor driver): TaskKilled (stage cancelled)
17/11/14 09:49:42 WARN TaskSetManager: Lost task 2.0 in stage 1.0 (TID 3, localhost, executor driver): TaskKilled (stage cancelled)
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_17 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_17 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN TaskSetManager: Lost task 17.0 in stage 1.0 (TID 18, localhost, executor driver): TaskKilled (stage cancelled)
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_0 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_0 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_0,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_9 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_9 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_9,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_13 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_13 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_7 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_18 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_1 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_18 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_1 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_13,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_7 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_18,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_3 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_3 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_12 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_12 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_11 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_11 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_16 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_16 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_10 failed due to an exception
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_10 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_1,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_10,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_16,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_11,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 WARN BlockManager: Putting block rdd_10_5 failed due to an exception
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_12,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 WARN BlockManager: Block rdd_10_5 could not be removed as it was not found on disk or in memory
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_3,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_7,StorageLevel(1 replicas),0,0))
17/11/14 09:49:42 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerBlockUpdated(BlockUpdatedInfo(BlockManagerId(driver, 172.17.0.12, 45999, None),rdd_10_5,StorageLevel(1 replicas),0,0))
```

`RuntimeError` in `bblfsh.filter` is thrown in case UAST is corrupted.

**Comment by vmarkovtsev** [comment]
Can be a problem on Python side, the uast iseem to be serialized.

**Comment by vmarkovtsev** [comment]
Yep, so far this is not an engine bug.
