### ISSUE TITLE
Improve error message when reading siva file fails

### ISSUE THREAD

**Issue by smacker** [src-d/engine#281]
## Expected Behavior

Error similar to this one (includes file name):

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 319 in stage 1.0 failed 4 times, most recent failure: Lost task 319.3 in stage 1.0 (TID 692, 10.2.15.79, executor 11): tech.sourced.siva.SivaException: Error reading index of 8691ebc26d12a9a9b8256ee165881d4c314c761c.siva.copy file.
```

## Current Behavior

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 415 in stage 1.0 failed 4 times, most recent failure: Lost task 415.3 in stage 1.0 (TID 1072, 10.2.15.79, executor 8): java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:869)
	at tech.sourced.siva.SivaReader.getEntry(SivaReader.java:42)
	at tech.sourced.engine.provider.RepositoryObjectFactory$$anonfun$genSivaRepository$1.apply(RepositoryProvider.scala:209)
```

## Context
I run gemini on relatively big dataset 10k repositories. It would be better to have processing without errors for my tests. The easiest way is to just delete this siva file. But without name it's not easy.

**Comment by erizocosmico** [comment]
Fixed in https://github.com/src-d/siva-java/pull/19, pending to be included in the engine itself.

**Comment by smacker** [comment]
wow. so fast! Thanks a lot, guys! No need for recursive `hadoop fs -du` around with sorting afterwards anymore! I just became a little bit happier 😅
