### ISSUE TITLE
Random failure due to cache

### ISSUE THREAD

**Issue by eiso** [src-d/engine#293]
**Version**: 0.3.3 (engine-jupyter docker container)

Running the following example code in a jupyter notebook, works initially but at some point starts throwing an error (see below)

```from sourced.engine import Engine
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder\
.master("local[*]").appName("Examples")\
.getOrCreate()

engine = Engine(spark, "/repositories", "standard")

head_blobs = engine.repositories.filter("is_fork = false").references\
.commits.first_reference_commit\
.tree_entries.blobs\
.classify_languages()\
.filter("is_binary = false")\
.select("blob_id", "path", "content", "lang").filter("lang is not null").cache()
```

Jupyter notebook warning:

```[I 14:25:23.680 NotebookApp] Saving file at /Example.ipynb
18/01/04 14:52:30 WARN GitOptimizer: Join cannot be optimized. It doesn't have GitRelations in both sides, or the Join type is not supported.
18/01/04 14:53:07 WARN GitOptimizer: Join cannot be optimized. It doesn't have GitRelations in both sides, or the Join type is not supported.
```
Spark errors:

```
-------------------------------------------------
Py4JJavaError   Traceback (most recent call last)
<ipython-input-63-7f70960763d9> in <module>()
----> 1 head_blobs = engine.repositories.filter("is_fork = false").references.commits.first_reference_commit.tree_entries.blobs.classify_languages().filter("is_binary = false").select("blob_id", "path", "content", "lang").filter("lang is not null").cache()

/usr/local/spark/python/pyspark/sql/dataframe.py in cache(self)
    508         """
    509         self.is_cached = True
--> 510         self._jdf.cache()
    511         return self
    512 

/usr/local/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/usr/local/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/local/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o1354.cache.
: org.apache.spark.SparkException: Join cannot be optimized. Invalid node: Join Inner, ((repository_id#5068 = repository_id#5076) && (reference_name#5077 = name#5069))
:- Project [repository_id#5076, reference_name#5077, hash#5079]
:  +- Filter (index#5078 = 0)
:     +- Relation[repository_id#5076,reference_name#5077,index#5078,hash#5079,message#5080,parents#5081,parents_count#5082,author_email#5083,author_name#5084,author_date#5085,committer_email#5086,committer_name#5087,committer_date#5088] GitRelation(org.apache.spark.sql.SparkSession@7c74a6a,StructType(StructField(repository_id,StringType,false), StructField(reference_name,StringType,false), StructField(index,IntegerType,false), StructField(hash,StringType,false), StructField(message,StringType,false), StructField(parents,ArrayType(StringType,false),true), StructField(parents_count,IntegerType,false), StructField(author_email,StringType,true), StructField(author_name,StringType,true), StructField(author_date,TimestampType,true), StructField(committer_email,StringType,true), StructField(committer_name,StringType,true), StructField(committer_date,TimestampType,true)),None,Some(commits))
+- Project [name#5069, repository_id#5068]
   +- InMemoryRelation [repository_id#5068, name#5069, hash#5070], true, 10000, StorageLevel(disk, memory, deserialized, 1 replicas)
         +- *Project [repository_id#710, name#711, hash#712]
            +- *Filter (isnotnull(is_fork#702) && (is_fork#702 = false))
               +- *Scan GitRelation(org.apache.spark.sql.SparkSession@7c74a6a,StructType(StructField(repository_id,StringType,false), StructField(name,StringType,false), StructField(hash,StringType,false), StructField(id,StringType,false), StructField(urls,ArrayType(StringType,false),false), StructField(is_fork,BooleanType,true), StructField(repository_path,StringType,true)),Some((repository_id#710 = id#700)),None) [repository_id#710,name#711,hash#712,is_fork#702] PushedFilters: [IsNotNull(is_fork), EqualTo(is_fork,false)], ReadSchema: struct<repository_id:string,name:string,hash:string>

	at tech.sourced.engine.rule.GitOptimizer$$anonfun$1.apply(SquashGitRelationsJoin.scala:124)
	at tech.sourced.engine.rule.GitOptimizer$$anonfun$1.apply(SquashGitRelationsJoin.scala:119)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$map$1.apply(TreeNode.scala:137)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$map$1.apply(TreeNode.scala:137)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:117)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreach$1.apply(TreeNode.scala:118)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreach$1.apply(TreeNode.scala:118)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:118)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreach$1.apply(TreeNode.scala:118)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreach$1.apply(TreeNode.scala:118)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:118)
	at org.apache.spark.sql.catalyst.trees.TreeNode.map(TreeNode.scala:137)
	at tech.sourced.engine.rule.GitOptimizer$.getJoinData(SquashGitRelationsJoin.scala:119)
	at tech.sourced.engine.rule.SquashGitRelationsJoin$$anonfun$apply$1.applyOrElse(SquashGitRelationsJoin.scala:24)
	at tech.sourced.engine.rule.SquashGitRelationsJoin$$anonfun$apply$1.applyOrElse(SquashGitRelationsJoin.scala:20)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:288)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
	at tech.sourced.engine.rule.SquashGitRelationsJoin$.apply(SquashGitRelationsJoin.scala:20)
	at tech.sourced.engine.rule.SquashGitRelationsJoin$.apply(SquashGitRelationsJoin.scala:18)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:78)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:78)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
	at org.apache.spark.sql.execution.CacheManager$$anonfun$cacheQuery$1.apply(CacheManager.scala:104)
	at org.apache.spark.sql.execution.CacheManager.writeLock(CacheManager.scala:68)
	at org.apache.spark.sql.execution.CacheManager.cacheQuery(CacheManager.scala:92)
	at org.apache.spark.sql.Dataset.persist(Dataset.scala:2513)
	at org.apache.spark.sql.Dataset.cache(Dataset.scala:2523)
	at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by erizocosmico** [comment]
This happens because when you use cache it becomes a `MemoryRelation`, which is then joined with a `GitRelation`, but `GitOptimizer` throws an error if a query can't be optimized instead of a warning as it did before.

@ajnavarro @mcarmonaa @jfontan I think we should revisit this decision and think about the bigger implications it may have, such as this one.

**Comment by mcarmonaa** [comment]
This happens with joins between `GitRelations` too if in its `Physical Plan` there are `Node`s different from `Filter`, `Project` or `LogicalRelation`.

```scala
import tech.sourced.engine._

val engine = Engine(spark, "/path/to/siva/files", "siva") 
val XLang: String = "Java"
val Year: Int = 2015

val commitsDf = engine.getRepositories.getReferences.getHEAD.getCommits

val yearDf = commitsDf
  .withColumn("year", year('committer_date))
  .filter('year === Year)
  .groupBy('repository_id)
  .min("year")
  .withColumnRenamed("min(year)", "year")

val langsDf = commitsDf.getBlobs.classifyLanguages

val languageDf = langsDf
  .groupBy('repository_id)
   .pivot("lang", Seq(XLang))
   .count()
   .filter(col(XLang).isNotNull)
   .orderBy(desc(XLang))]

languageDf.join(yearDf, "repository_id").show
```

Outcome:

```
scala> languageDf.join(yearDf, "repository_id").show
18/01/05 10:03:29 WARN Utils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.debug.maxToStringFields' in SparkEnv.conf.
org.apache.spark.SparkException: Join cannot be optimized. Invalid node: Sort [Java#355L DESC NULLS LAST], true
+- Project [repository_id#62, __pivot_count(1) AS `count` AS `count(1) AS ``count```#354[0] AS Java#355L]
   +- Filter isnotnull(__pivot_count(1) AS `count` AS `count(1) AS ``count```#354[0])
      +- Aggregate [repository_id#62], [repository_id#62, pivotfirst(lang#329, count(1) AS `count`#350L, Java, 0, 0) AS __pivot_count(1) AS `count` AS `count(1) AS ``count```#354]
         +- Aggregate [repository_id#62, lang#329], [repository_id#62, lang#329, count(1) AS count(1) AS `count`#350L]
            +- Project [repository_id#62, UDF(is_binary#65, path#51, content#64) AS lang#329]
               +- Filter (((reference_name#21 = refs/heads/HEAD) || (reference_name#21 = HEAD)) && ((name#11 = refs/heads/HEAD) || (name#11 = HEAD)))
                  +- Relation[blob_id#60,commit_hash#61,repository_id#62,reference_name#63,content#64,is_binary#65,commit_hash#48,repository_id#49,reference_name#50,path#51,blob#52,repository_id#20,reference_name#21,index#22,hash#23,message#24,parents#25,parents_count#26,author_email#27,author_name#28,author_date#29,committer_email#30,committer_name#31,committer_date#32,... 8 more fields] GitRelation(org.apache.spark.sql.SparkSession@6720c88b,StructType(StructField(blob_id,StringType,false), StructField(commit_hash,StringType,false), StructField(repository_id,StringType,false), StructField(reference_name,StringType,false), StructField(content,BinaryType,true), StructField(is_binary,BooleanType,false), StructField(commit_hash,StringType,false), StructField(repository_id,StringType,false), StructField(reference_name,StringType,false), StructField(path,StringType,false), StructField(blob,StringType,false), StructField(repository_id,StringType,false), StructField(reference_name,StringType,false), StructField(index,IntegerType,false), StructField(hash,StringType,false), StructField(message,StringType,false), StructField(parents,ArrayType(StringType,false),true), StructField(parents_count,IntegerType,false), StructField(author_email,StringType,true), StructField(author_name,StringType,true), StructField(author_date,TimestampType,true), StructField(committer_email,StringType,true), StructField(committer_name,StringType,true), StructField(committer_date,TimestampType,true), StructField(repository_id,StringType,false), StructField(name,StringType,false), StructField(hash,StringType,false), StructField(is_remote,BooleanType,false), StructField(id,StringType,false), StructField(urls,ArrayType(StringType,false),false), StructField(is_fork,BooleanType,true), StructField(repository_path,StringType,true)),Some(((blob#52 = blob_id#60) && ((commit_hash#48 = hash#23) && (((repository_id#10 = repository_id#20) && (reference_name#21 = name#11)) && (repository_id#10 = id#0))))),None)

  at tech.sourced.engine.rule.GitOptimizer$$anonfun$1.apply(SquashGitRelationsJoin.scala:139)
  at tech.sourced.engine.rule.GitOptimizer$$anonfun$1.apply(SquashGitRelationsJoin.scala:119)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$map$1.apply(TreeNode.scala:137)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$map$1.apply(TreeNode.scala:137)
  at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:117)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreach$1.apply(TreeNode.scala:118)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreach$1.apply(TreeNode.scala:118)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:118)
  at org.apache.spark.sql.catalyst.trees.TreeNode.map(TreeNode.scala:137)
  at tech.sourced.engine.rule.GitOptimizer$.getJoinData(SquashGitRelationsJoin.scala:119)
  at tech.sourced.engine.rule.SquashGitRelationsJoin$$anonfun$apply$1.applyOrElse(SquashGitRelationsJoin.scala:24)
  at tech.sourced.engine.rule.SquashGitRelationsJoin$$anonfun$apply$1.applyOrElse(SquashGitRelationsJoin.scala:20)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$2.apply(TreeNode.scala:293)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$2.apply(TreeNode.scala:293)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:292)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
  at tech.sourced.engine.rule.SquashGitRelationsJoin$.apply(SquashGitRelationsJoin.scala:20)
  at tech.sourced.engine.rule.SquashGitRelationsJoin$.apply(SquashGitRelationsJoin.scala:18)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:2832)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2153)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2366)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:245)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:644)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:603)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:612)
  ... 50 elided

```

**Comment by erizocosmico** [comment]
This is removed in #308 and logged as a very dangerously-looking warning
