### ISSUE TITLE
Parsing csharp files does not work

### ISSUE THREAD

**Issue by dpordomingo** [src-d/engine#296]
discovered at https://github.com/src-d/empathy-sessions/issues/37#issuecomment-470045137

caused by https://github.com/bblfsh/csharp-driver/issues/32
caused by https://github.com/bblfsh/bblfshd/issues/259
might be related to https://github.com/src-d/engine/issues/270

Running parse over a `.cs` file, and asking for `csharp` lang takes forever:

```shell
$ srcd parse uast examples/example.cs --lang csharp
INFO[0003] if this is the first time using a driver for a language,
this might take a few more minutes while we install it 
```

but if you check the container's logs there is a panic that is not exported in source{d} Engine logs, what is wrong.

```shell
docker logs -f srcd-cli-bblfshd

panic: invalid tracer configuration: lookup localhost on 1.1.1.1:53: no such host

goroutine 1 [running]:
github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server.RunNative(0xba9260, 0xc4200be180, 0xb139e9, 0x6, 0xc420357ac0, 0x1, 0x1, 0xf0a260, 0x2, 0x2, ...)
	/go/src/github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server/common.go:35 +0x162
github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server.Run(0xb139e9, 0x6, 0xc420357ac0, 0x1, 0x1, 0xf0a260, 0x2, 0x2, 0xc4203bd5a0, 0x2, ...)
	/go/src/github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server/common.go:20 +0x74
main.main()
	/go/src/github.com/bblfsh/csharp-driver/driver/main.go:11 +0x5a
```

and if you `CTRL+C` on `srcd parse uast` tab, the container will log:

```
time="2019-03-04T12:34:37Z" level=error msg="error selecting pool:
                            unexpected error: context canceled"
time="2019-03-04T12:34:37Z" level=error msg="request processed content 348 bytes error:
                            unexpected error: context canceled" elapsed=13.66024993s
                            filename="/projects/src/github.com/src-d/lookout/doc.go"
                            language=csharp
```

**Comment by carlosms** [comment]
We should test if this was fixed after the update to bblfshd 2.12.

**Comment by dpordomingo** [comment]
I'll do so once it has been released :dancer:

**Comment by se7entyse7en** [comment]
Seems to be working now (engine version v0.12.0). I've tested with hello world in C#.
```
using System;

class HelloWorldApp
{
    public static void Main(string[] args)
  {
    Console.WriteLine("Hello World");
    Console.ReadLine ();
  }
}
```

<img width="1061" alt="Screenshot 2019-04-04 at 17 23 43" src="https://user-images.githubusercontent.com/5599208/55567687-7cfabd80-56fe-11e9-8471-75d1bd86c2b8.png">
