### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/engine#319]
I am running the following command on staging:

```
pyspark --py-files sourced-engine.zip -c 'spark.local.dir=/spark-temp-data' --driver-memory 16G --executor-memory 4G --total-executor-cores 48 --maste
r "spark://p-spark-master:7077" --packages "tech.sourced:engine:0.3.6"

>>> from sourced.engine import Engine
>>> engine = Engine(spark, "hdfs://hdfs-namenode/apps/borges/root-repositories", "siva")
>>> engine.repositories.count()
```

I get the following stack after ~2000 jobs:

```
[Stage 0:=======>                                           (1938 + 48) / 12932]18/01/19 18:20:42 WARN TaskSetManager: Lost task 1953.0 in stage 0.0 (TID 1954, 10.2.15.90
, executor 1): java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.xerces.xni.XMLString.toString(Unknown Source)
        at org.apache.xerces.parsers.AbstractDOMParser.characters(Unknown Source)
        at org.apache.xerces.xinclude.XIncludeHandler.characters(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:150)
        at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2480)
        at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2468)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2539)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2492)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2405)
        at org.apache.hadoop.conf.Configuration.clear(Configuration.java:2434)
        at org.apache.hadoop.conf.Configuration.readFields(Configuration.java:2870)
        at org.apache.spark.input.PortableDataStream.conf$lzycompute(PortableDataStream.scala:164)
        at org.apache.spark.input.PortableDataStream.conf(PortableDataStream.scala:161)
        at org.apache.spark.input.PortableDataStream.getConfiguration(PortableDataStream.scala:203)
        at tech.sourced.engine.provider.RepositoryProvider$.keyForSource(RepositoryProvider.scala:261)
        at tech.sourced.engine.provider.RepositoryProvider.get(RepositoryProvider.scala:56)
        at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:87)
        at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:85)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)

[Stage 0:=======>                                           (1944 + 48) / 12932]18/01/19 18:21:11 WARN TaskSetManager: Lost task 1942.0 in stage 0.0 (TID 1943, 10.2.15.90
, executor 1): java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:84)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:59)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:119)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:366)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:338)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:289)
        at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2034)
        at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2003)
        at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:1979)
        at tech.sourced.engine.provider.RepositoryObjectFactory.genSivaRepository(RepositoryProvider.scala:193)
        at tech.sourced.engine.provider.RepositoryObjectFactory.create(RepositoryProvider.scala:93)
        at tech.sourced.engine.provider.RepositoryObjectFactory.create(RepositoryProvider.scala:87)
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:60)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1064)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:358)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:281)
        at tech.sourced.engine.provider.RepositoryProvider.get(RepositoryProvider.scala:47)
        at tech.sourced.engine.provider.RepositoryProvider.get(RepositoryProvider.scala:56)
        at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:87)
        at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:85)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)

[Stage 0:=======>                                           (1949 + 48) / 12932]18/01/19 18:21:32 WARN TaskSetManager: Lost task 1972.0 in stage 0.0 (TID 1973, 10.2.15.90
, executor 1): java.lang.OutOfMemoryError: GC overhead limit exceeded

[Stage 0:=======>                                           (1953 + 48) / 12932]18/01/19 18:21:44 WARN TaskSetManager: Lost task 1979.0 in stage 0.0 (TID 1980, 10.2.101.1
24, executor 0): java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.xerces.dom.DeferredDocumentImpl.createChunk(Unknown Source)
        at org.apache.xerces.dom.DeferredDocumentImpl.ensureCapacity(Unknown Source)
        at org.apache.xerces.dom.DeferredDocumentImpl.createNode(Unknown Source)
        at org.apache.xerces.dom.DeferredDocumentImpl.createDeferredTextNode(Unknown Source)
        at org.apache.xerces.parsers.AbstractDOMParser.characters(Unknown Source)
        at org.apache.xerces.xinclude.XIncludeHandler.characters(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:150)
        at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2480)
        at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2468)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2539)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2492)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2405)
        at org.apache.hadoop.conf.Configuration.clear(Configuration.java:2434)
        at org.apache.hadoop.conf.Configuration.readFields(Configuration.java:2870)
        at org.apache.spark.input.PortableDataStream.conf$lzycompute(PortableDataStream.scala:164)
        at org.apache.spark.input.PortableDataStream.conf(PortableDataStream.scala:161)
        at org.apache.spark.input.PortableDataStream.getConfiguration(PortableDataStream.scala:203)
        at tech.sourced.engine.provider.RepositoryProvider$.keyForSource(RepositoryProvider.scala:261)
        at tech.sourced.engine.provider.RepositoryProvider.get(RepositoryProvider.scala:56)
        at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:87)
        at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:85)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)

18/01/19 18:22:00 WARN TaskSetManager: Lost task 1954.1 in stage 0.0 (TID 1988, 10.2.101.124, executor 0): java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:88)
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.<init>(ZipFile.java:393)
        at java.util.zip.ZipFile.getInputStream(ZipFile.java:374)
        at java.util.jar.JarFile.getInputStream(JarFile.java:447)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:162)
        at java.net.URL.openStream(URL.java:1045)
        at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2468)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2539)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2492)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2405)
        at org.apache.hadoop.conf.Configuration.clear(Configuration.java:2434)
        at org.apache.hadoop.conf.Configuration.readFields(Configuration.java:2870)
        at org.apache.spark.input.PortableDataStream.conf$lzycompute(PortableDataStream.scala:164)
        at org.apache.spark.input.PortableDataStream.conf(PortableDataStream.scala:161)
        at org.apache.spark.input.PortableDataStream.getConfiguration(PortableDataStream.scala:203)
        at tech.sourced.engine.provider.RepositoryProvider$.keyForSource(RepositoryProvider.scala:261)
        at tech.sourced.engine.provider.RepositoryProvider.get(RepositoryProvider.scala:56)
        at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:87)
        at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:85)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)

[Stage 0:=======>                                           (1954 + 48) / 12932]18/01/19 18:22:12 WARN TaskSetManager: Lost task 1985.0 in stage 0.0 (TID 1986, 10.2.15.90
, executor 1): java.lang.OutOfMemoryError: GC overhead limit exceeded

18/01/19 18:22:27 WARN TaskSetManager: Lost task 1962.0 in stage 0.0 (TID 1963, 10.2.101.124, executor 0): java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.String.toCharArray(String.java:2899)
        at java.util.zip.ZipCoder.getBytes(ZipCoder.java:78)
        at java.util.zip.ZipFile.getEntry(ZipFile.java:310)
        at java.util.jar.JarFile.getEntry(JarFile.java:240)
        at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
        at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1005)
        at sun.misc.URLClassPath$JarLoader.findResource(URLClassPath.java:983)
        at sun.misc.URLClassPath.findResource(URLClassPath.java:188)
        at java.net.URLClassLoader$2.run(URLClassLoader.java:569)
        at java.net.URLClassLoader$2.run(URLClassLoader.java:567)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findResource(URLClassLoader.java:566)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1096)
        at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:232)
        at org.apache.xerces.parsers.SecuritySupport$6.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.xerces.parsers.SecuritySupport.getResourceAsStream(Unknown Source)
        at org.apache.xerces.parsers.ObjectFactory.findJarServiceProvider(Unknown Source)
        at org.apache.xerces.parsers.ObjectFactory.createObject(Unknown Source)
        at org.apache.xerces.parsers.ObjectFactory.createObject(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.<init>(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.<init>(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.<init>(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(Unknown Source)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2530)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2492)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2405)
        at org.apache.hadoop.conf.Configuration.clear(Configuration.java:2434)
        at org.apache.hadoop.conf.Configuration.readFields(Configuration.java:2870)
        at org.apache.spark.input.PortableDataStream.conf$lzycompute(PortableDataStream.scala:164)
        at org.apache.spark.input.PortableDataStream.conf(PortableDataStream.scala:161)
        at org.apache.spark.input.PortableDataStream.getConfiguration(PortableDataStream.scala:203)

18/01/19 18:22:43 WARN TaskSetManager: Lost task 1996.0 in stage 0.0 (TID 2001, 10.2.15.90, executor 1): java.lang.OutOfMemoryError: GC overhead limit exceeded
```

I suggest adding a configurable size threshold to skip large siva files to reduce the probability of such disappointing errors after 4 hours of runtime :) Also we will be able to accurately measure the peak threshold and write sane docs about how to select it (e.g. 100MB if 1GB memory, 1GB if 4GB, etc.).

**Comment by vmarkovtsev** [comment]
I also tested 8GB and 12GB executor memory. Same error.

**Comment by ajnavarro** [comment]
Try with ` engine.repositories.select("id").count()`. That will reduce the serialization time due to be able to push down projections to the relation.

**Comment by jfontan** [comment]
I've managed to reproduce the problem locally with a set of 9000 siva files, most of them small and a big one (2.6Gb). Process memory limited to 1Gb.

* Siva files stored locally **OK**
* Siva files stored in HDFS **Out of memory**
* Only small siva files in HDFS **OK**

There seems to be a problem when big files need to be copied using HDFS client. I'm still investigating the issue.

**Comment by vmarkovtsev** [comment]
That's awesome @jfontan! Can't wait for the fix :laughing:
