### ISSUE TITLE
Job fails with org.eclipse.jgit.errors.MissingObjectException: Missing commit

### ISSUE THREAD

**Issue by smacker** [src-d/engine#323]
## Expected Behavior
Error should include siva file name or there should be option to skip errors.

## Current Behavior
```
$ ./gemini-k8s-cluster hash hdfs://hdfs-namenode/apps/borges/1k
Using spark-submit from /usr/local/spark
Hashing 923 repositories in: hdfs://hdfs-namenode/apps/borges/1k
[Stage 1:>                                                        (0 + 28) / 28]ERROR 18:29:53 org.apache.spark.internal.Logging$class (Logging.scala:70) - Task 22 in stage 0.0 failed 4 times; aborting job
[Stage 1:==========================>                             (13 + 15) / 28]ERROR 18:30:05 org.apache.spark.internal.Logging$class (Logging.scala:70) - Task 22 in stage 1.0 failed 4 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 22 in stage 1.0 failed 4 times, most recent failure: Lost task 22.3 in stage 1.0 (TID 70, 10.2.36.12, executor 40): org.eclipse.jgit.errors.MissingObjectException: Missing commit 6117ae6cb7492916815d078dfa26abc0362f30e1
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:164)
	at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:903)
	at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:155)
	at org.eclipse.jgit.revwalk.RevWalk.markStart(RevWalk.java:293)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:339)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:198)
	at tech.sourced.engine.iterator.RefWithCommitIterator.liftedTree1$1(CommitIterator.scala:145)
	at tech.sourced.engine.iterator.RefWithCommitIterator.hasNext(CommitIterator.scala:143)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
	at tech.sourced.engine.iterator.ChainableIterator.hasNext(ChainableIterator.scala:89)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:330)
	at tech.sourced.engine.iterator.ChainableIterator.isEmpty(ChainableIterator.scala:16)
	at tech.sourced.engine.iterator.ChainableIterator.hasNext(ChainableIterator.scala:78)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:330)
	at tech.sourced.engine.iterator.ChainableIterator.isEmpty(ChainableIterator.scala:16)
	at tech.sourced.engine.iterator.ChainableIterator.hasNext(ChainableIterator.scala:78)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at tech.sourced.engine.iterator.CleanupIterator.hasNext(CleanupIterator.scala:23)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at com.datastax.spark.connector.util.CountingIterator.hasNext(CountingIterator.scala:12)
	at com.datastax.spark.connector.writer.GroupingBatchBuilder.next(GroupingBatchBuilder.scala:105)
	at com.datastax.spark.connector.writer.GroupingBatchBuilder.next(GroupingBatchBuilder.scala:31)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at com.datastax.spark.connector.writer.GroupingBatchBuilder.foreach(GroupingBatchBuilder.scala:31)
	at com.datastax.spark.connector.writer.TableWriter$$anonfun$writeInternal$1.apply(TableWriter.scala:233)
	at com.datastax.spark.connector.writer.TableWriter$$anonfun$writeInternal$1.apply(TableWriter.scala:210)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:112)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:111)
	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:145)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111)
	at com.datastax.spark.connector.writer.TableWriter.writeInternal(TableWriter.scala:210)
	at com.datastax.spark.connector.writer.TableWriter.insert(TableWriter.scala:197)
	at com.datastax.spark.connector.writer.TableWriter.write(TableWriter.scala:183)
	at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:36)
	at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:36)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

## Steps to Reproduce (for bugs)
```
spark-shell --packages "tech.sourced:engine:0.3.6" --master="spark://p-spark-master:7077"

scala> import tech.sourced.engine._
import tech.sourced.engine._

scala> val engine = Engine(spark, "hdfs://hdfs-namenode/apps/borges/1k", "siva")
engine: tech.sourced.engine.Engine = tech.sourced.engine.Engine@1e08f0cd

scala> engine.getRepositories.getHEAD.getCommits.getFirstReferenceCommit.count()
[Stage 2:=>                                                       (1 + 36) / 37]
18/01/25 18:38:48 WARN TaskSetManager: Lost task 34.0 in stage 2.0 (TID 73, 10.2.101.126, executor 0): org.eclipse.jgit.errors.MissingObjectException: Missing commit fcecd0165baec9ea25ed500919810f7f3603732d
```

## Context
Run gemini

## Your Environment (for bugs)
* Version used: 0.3.6
* Src-d staging cluster

**Comment by bzz** [comment]
@erizocosmico so cool, thank you for fixing it! 
Happy to test it using https://github.com/src-d/engine/releases/tag/v0.5.1
