### ISSUE TITLE
pip installs local version 

### ISSUE THREAD

**Issue by zurk** [src-d/engine#324]
## Expected Behavior
`pip3 install sourced-engine==0.4.0` or `pip3 install sourced-engine==3.6.0` should install python package with provided version. So if I run `pip list | grep engine` I should get something like 
`sourced-engine (0.4.0)`

## Current Behavior
`pip list | grep engine` returns `sourced-engine (local)`

## Possible Solution
As I can see in [setup.py](https://github.com/src-d/engine/blob/master/python/setup.py) you need to add special file before each release called `version.txt`

I am not sure it is the best way to specify the version. Maybe better to keep it and bump before each release in `setup.py`?

## Steps to Reproduce (for bugs)

```bash
pip3 install sourced-engine
pip list | grep sourced
```

## Context
I am trying to use our docker image in https://github.com/src-d/ml and it fails with the message:
```bash
>>> docker run srcdml
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (sourced-engine local (/usr/local/lib/python3.5/dist-packages), Requirement.parse('sourced-engine<0.4,>=0.3.0'), {'sourced-ml'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/srcml", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sourced-engine<0.4,>=0.3.0' distribution was not found and is required by sourced-ml
```

**Comment by erizocosmico** [comment]
Version file should add itself in the CI (it did, at least). Manually bumping version is not an option, it's too error prone.

**Comment by zurk** [comment]
just want to say that this bug remained in the new 0.5.0 version.

**Comment by erizocosmico** [comment]
Yes, it has not been fixed yet.
