### ISSUE TITLE
TestWebTestSuite/TestParse is flaky

### ISSUE THREAD

**Issue by smacker** [src-d/engine#370]
```
=== RUN   TestWebTestSuite/TestParse
SIGQUIT: quit
PC=0x475638 m=0 sigcode=0
goroutine 794 [syscall, 7 minutes]:
syscall.Syscall6(0xf7, 0x1, 0xaa4, 0xc0002db608, 0x1000004, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/syscall/asm_linux_amd64.s:44 +0x5 fp=0xc0002db5b8 sp=0xc0002db5b0 pc=0x475615
os.(*Process).blockUntilWaitable(0xc0003a5e30, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/os/wait_waitid.go:31 +0x98 fp=0xc0002db6a8 sp=0xc0002db5b8 pc=0x498da8
os.(*Process).wait(0xc0003a5e30, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/os/exec_unix.go:22 +0x39 fp=0xc0002db720 sp=0xc0002db6a8 pc=0x491529
os.(*Process).Wait(...)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc0003ba840, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/os/exec/exec.go:474 +0x61 fp=0xc0002db798 sp=0xc0002db720 pc=0x8b1161
github.com/src-d/engine/cmd/srcd/cmd.(*WebTestSuite).testCommon.func1(0xc000229860, 0xc0003ba840)
	/home/travis/gopath/src/github.com/src-d/engine/cmd/srcd/cmd/web_test.go:46 +0x2b fp=0xc0002db7d0 sp=0xc0002db798 pc=0x9aeaeb
runtime.goexit()
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0002db7d8 sp=0xc0002db7d0 pc=0x45e331
created by github.com/src-d/engine/cmd/srcd/cmd.(*WebTestSuite).testCommon
	/home/travis/gopath/src/github.com/src-d/engine/cmd/srcd/cmd/web_test.go:45 +0x283

goroutine 1 [chan receive, 7 minutes]:
testing.(*T).Run(0xc000487d00, 0xb48e0d, 0x10, 0xb6e9d0, 0x481701)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc0000b9400)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc0000b9400, 0xc00018de30)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:865 +0xc0
testing.runTests(0xc0001e1480, 0x112a4a0, 0x7, 0x7, 0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc0000ffc80, 0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:1072 +0x162
main.main()
	_testmain.go:54 +0x13e
```

**Comment by smacker** [comment]
A bit more context: I saw it only on Travis and not very often.
