### ISSUE TITLE
MissingObjectException on tree iterator

### ISSUE THREAD

**Issue by smola** [src-d/engine#374]
## Expected Behavior
Queries working on all tree entries for our siva datasets.

## Current Behavior
Query:

```sql
SELECT
    token,
    COUNT(DISTINCT repository_id) AS repository_count
FROM (
    SELECT
        b.repository_id,
        EXPLODE(SPLIT(b.content, '[^_A-Za-z0-9]+')) AS token
    FROM
        blobs b
        JOIN repository_ids_no_forks r ON
            b.repository_id = r.repository_id
    WHERE
        reference_name = 'refs/heads/HEAD' AND
        is_binary = false AND
        LENGTH(content) < 524288
) AS q
GROUP BY token
ORDER BY repository_count DESC
LIMIT 50
```

Dataset: `/100-siva` (in our staging cluster).

Crash:

```
Job aborted due to stage failure: Task 2 in stage 28.0 failed 1 times, most recent failure: Lost task 2.0 in stage 28.0 (TID 2216, localhost, executor driver): tech.sourced.engine.iterator.RepositoryException: Repository error with data: Repository[/tmp/spark-c3e0aed7-dd88-448b-bfd4-22aec9cc156e/processing-repositories/B25E14E8CC093B899869839601B14C54/386bc1ad519609dc6ece05296a80c003d4c8e107.siva]; urls git://github.com/WarlordCore/Justice-Core, git@github.com:WarlordCore/Justice-Core.git, https://github.com/WarlordCore/Justice-Core.git
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing tree 0ba835cd5bafc7ed2ccf90d67b882a696af51771
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:164)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:214)
	at org.eclipse.jgit.treewalk.TreeWalk.parserFor(TreeWalk.java:1347)
	at org.eclipse.jgit.treewalk.TreeWalk.addTree(TreeWalk.java:741)
	at tech.sourced.engine.iterator.GitTreeEntryIterator$.tech$sourced$engine$iterator$GitTreeEntryIterator$$getTreeEntries(GitTreeEntryIterator.scala:146)
	at tech.sourced.engine.iterator.GitTreeEntryIterator$$anonfun$1.apply(GitTreeEntryIterator.scala:124)
	at tech.sourced.engine.iterator.GitTreeEntryIterator$$anonfun$1.apply(GitTreeEntryIterator.scala:124)
```

## Possible Solution
Similar to the other iterator fixes for jgit exceptions.

## Steps to Reproduce
1. Execute the above query in our cluster.

## Context
Two of our (tentative) reference SQL queries give this error with a relatively small dataset found in our staging cluster.

## Your Environment
* Version used: plain jupyter + `---packages tech.sourced:engine:0.5.7`
* Operating System and version: kubernetes (staging cluster)

**Comment by bzz** [comment]
I guess that this might be handled by https://github.com/src-d/engine/issues/367
