### ISSUE TITLE
Engine fails to extract UASTs on actual Spark cluster

### ISSUE THREAD

**Issue by bzz** [src-d/engine#402]
When running on local mode with `--packages "tech.sourced:engine:0.6.3"` -  extracting UASTs works. 

But after switching to actual Apache Spark cluster with the same params and query i.e in Standalone mode - `extractUAST` fails with 
```
java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.createUnstarted()Lcom/google/common/base/Stopwatch;
```

## Expected Behavior
get the number of UASTs

## Current Behavior
`java.lang.NoSuchMethodError`

<details>
```
18/06/18 10:39:00 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, 192.168.1.37, executor 0): java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.createUnstarted()Lcom/google/common/base/Stopwatch;
	at io.grpc.internal.GrpcUtil$4.get(GrpcUtil.java:566)
	at io.grpc.internal.GrpcUtil$4.get(GrpcUtil.java:563)
	at io.grpc.internal.CensusStatsModule$ClientCallTracer.<init>(CensusStatsModule.java:333)
	at io.grpc.internal.CensusStatsModule.newClientCallTracer(CensusStatsModule.java:137)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor.interceptCall(CensusStatsModule.java:672)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:104)
	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:636)
	at gopkg.in.bblfsh.sdk.v1.protocol.generated.ProtocolServiceGrpc$ProtocolServiceBlockingStub.parse(ProtocolServiceGrpc.scala:61)
	at org.bblfsh.client.BblfshClient.parse(BblfshClient.scala:30)
	at tech.sourced.engine.util.Bblfsh$.extractUAST(Bblfsh.scala:80)
	at tech.sourced.engine.udf.ExtractUASTsUDF$class.extractUASTs(ExtractUASTsUDF.scala:17)
	at tech.sourced.engine.udf.ExtractUASTsUDF$.extractUASTs(ExtractUASTsUDF.scala:24)
	at tech.sourced.engine.package$EngineDataFrame$$anon$2.call(package.scala:395)
	at tech.sourced.engine.package$EngineDataFrame$$anon$2.call(package.scala:377)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
```
</details>

## Possible Solution
 - update the build, so final fatJar avoids calling un-shaded version of Guava
 - Add TravisCI profile that runs this query on actual local Apache Spark standalone cluster

## Steps to Reproduce (for bugs)
1. Start Apache Spark in a cluster mode and a `spark-shell` \w Engine
   ```
   export MASTER_HOST=127.0.0.1
   $SPARK_HOME/sbin/start-master.sh -h $MASTER_HOST -p 7077
   $SPARK_HOME/sbin/start-slave.sh $MASTER_HOST:7077
   $SPARK_HOME/bin/spark-shell --master "spark://$MASTER_HOST:7077" --packages 
   "tech.sourced:engine:0.6.3"
   ```
2. Run `extractUASTs` 
   ```scala
   import tech.sourced.engine._
   val path = "<path-to-siva-files>"
   val engine = Engine(spark, path, "siva")
   
   val repos = engine.getRepositories
   val files = repos.getHEAD
        .getCommits
        .getTreeEntries
        .getBlobs
   val uast = files.extractUASTs
   
   uast.count
   ```

## Context
This mimics the file-duplication workflow we have in Gemini on hash. Ability to reproduce it in spark-shell is crucial for debugging.

## Your Environment (for bugs)

* Spark version: 2.2.0
* Engine version: 0.6.3
* Operating System and version: Linux/macOS

**Comment by bzz** [comment]
Update: this seems to be related with how `--packages` in Apache Spark work 😕 

If `spark-shell` is started with:
 - `--packages "tech.sourced:engine:0.6.3"`     -> **`java.lang.NoSuchMethodError`**
 - `--jars <path-to-engine>/target/engine-0.6.3.jar` -> **works as expected**

**Comment by smola** [comment]
`--packages` used to work for me. This seems to be the usual dependency hell with conflicting Guava versions.

**Comment by ajnavarro** [comment]
@bzz maybe can be related with some kind of cache used by the `--packages` command?

**Comment by bzz** [comment]
True. And packages used to work for me as well.

**Comment by smacker** [comment]
@bzz it's a cache on master (or workers) side. I used to have the same problem. Removing cache helped. Reference: https://github.com/src-d/engine/issues/389
